{
"type": "FeatureCollection",
"name": "DerivadosPetrol",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": 6374050, "clee": "20079324120000011000009924S2", "nom_estab": "ERGON ASFALTO MEXICO", "raz_social": "ERGON ASFALTOS MEXICO S DE RL DE CV", "codigo_act": 324120, "nombre_act": "Fabricación de productos de asfalto", "per_ocu": "11 a 30 personas", "tipo_vial": "CIRCUITO", "nom_vial": "OLEODUCTO GENERAL LAZARO CARDENAS", "tipo_v_e_1": "CALLE", "nom_v_e_1": "JESÚS RASGADO", "tipo_v_e_2": "CALLE", "nom_v_e_2": "HUMBERTO BEJARANO", "tipo_v_e_3": "CALLE", "nom_v_e_3": "ÁLVARO CARRILLO", "numero_ext": 0, "letra_ext": "SN", "edificio": null, "edificio_e": null, "numero_int": 0, "letra_int": null, "tipo_asent": "PARQUE INDUSTRIAL", "nomb_asent": "COMPLEMENTARIO FONDEPORT", "tipoCenCom": "OTRO CONGLOMERADO", "nom_CenCom": "COMPLEMENTARIO", "num_local": null, "cod_postal": 70610, "cve_ent": 20, "entidad": "Oaxaca", "cve_mun": 79, "municipio": "Salina Cruz", "cve_loc": 36, "localidad": "Puerto de Salina Cruz [Parque Industrial y Complementario]                                                    ", "ageb": "0116", "manzana": 2, "telefono": null, "correoelec": null, "www": null, "tipoUniEco": "Fijo", "latitud": 16.22149526, "longitud": -95.18907836, "fecha_alta": "2010-07" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -95.18907836, 16.22149526 ] ] } },
{ "type": "Feature", "properties": { "id": 6515127, "clee": "20079324110000017000003129S0", "nom_estab": "REFINERIA SALINA CRUZ ANTONIO DOVALI JAIME", "raz_social": "PEMEX TRANSFORMACIÓN INDUSTRIAL ", "codigo_act": 324110, "nombre_act": "Refinación de petróleo", "per_ocu": "251 y más personas", "tipo_vial": null, "nom_vial": "OLEODUCTO GENERAL LAZARO CARDENAS", "tipo_v_e_1": null, "nom_v_e_1": "NINGUNO", "tipo_v_e_2": null, "nom_v_e_2": "A LA REFINERIA", "tipo_v_e_3": null, "nom_v_e_3": null, "numero_ext": null, "letra_ext": "KM 3", "edificio": null, "edificio_e": null, "numero_int": null, "letra_int": null, "tipo_asent": "OTRO (ESPECIFIQUE)", "nomb_asent": "NINGUNO", "tipoCenCom": null, "nom_CenCom": null, "num_local": null, "cod_postal": null, "cve_ent": 20, "entidad": "Oaxaca", "cve_mun": 79, "municipio": "Salina Cruz", "cve_loc": 1, "localidad": "Salina Cruz                                                                                                   ", "ageb": "0440", "manzana": 1, "telefono": null, "correoelec": null, "www": null, "tipoUniEco": "Fijo", "latitud": 16.21919167, "longitud": -95.19025327, "fecha_alta": "2016-01" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -95.19025327, 16.21919167 ] ] } },
{ "type": "Feature", "properties": { "id": 6515150, "clee": "30108324110000017000003129S5", "nom_estab": "REFINERIA MINATITLAN GENERAL LAZARO CARDENAS", "raz_social": "PEMEX TRANSFORMACIÓN INDUSTRIAL ", "codigo_act": 324110, "nombre_act": "Refinación de petróleo", "per_ocu": "251 y más personas", "tipo_vial": null, "nom_vial": "Primero de Mayo", "tipo_v_e_1": "CALLE", "nom_v_e_1": "Manuel Ávila Camacho", "tipo_v_e_2": "CALLE", "nom_v_e_2": "Simón Bolívar", "tipo_v_e_3": "PRIVADA", "nom_v_e_3": "Ninguno", "numero_ext": 119, "letra_ext": null, "edificio": null, "edificio_e": null, "numero_int": 0, "letra_int": null, "tipo_asent": "COLONIA", "nomb_asent": "OBRERA", "tipoCenCom": null, "nom_CenCom": null, "num_local": null, "cod_postal": 96740, "cve_ent": 30, "entidad": "Veracruz de Ignacio de la Llave", "cve_mun": 108, "municipio": "Minatitlán", "cve_loc": 1, "localidad": "Minatitlán                                                                                                    ", "ageb": "0630", "manzana": 1, "telefono": null, "correoelec": null, "www": null, "tipoUniEco": "Fijo", "latitud": 17.9856619, "longitud": -94.53416261, "fecha_alta": "2016-01" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -94.53416261, 17.9856619 ] ] } }
]
}
