{
"type": "FeatureCollection",
"name": "EquipoCompu",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": 7401675, "clee": "30141334220000011000000000U4", "nom_estab": "ANTENAS PARA TV", "raz_social": null, "codigo_act": 334220, "nombre_act": "Fabricación de equipo de transmisión y recepción de señales de radio y televisión, y equipo de comunicación inalámbrico", "per_ocu": "0 a 5 personas", "tipo_vial": "CALLE", "nom_vial": "JOSE AZUETA", "tipo_v_e_1": "CALLE", "nom_v_e_1": "ERASMO CASTELLANOS QUINTO", "tipo_v_e_2": "CALLE", "nom_v_e_2": "PRIMITIVO R VALENCIA", "tipo_v_e_3": "CALLE", "nom_v_e_3": "VIRGILIO URIBE", "numero_ext": null, "letra_ext": "SN", "edificio": null, "edificio_e": null, "numero_int": null, "letra_int": null, "tipo_asent": "COLONIA", "nomb_asent": "CERRO AMARILLO DE ABAJO", "tipoCenCom": null, "nom_CenCom": null, "num_local": null, "cod_postal": 95800, "cve_ent": 30, "entidad": "Veracruz de Ignacio de la Llave", "cve_mun": 141, "municipio": "San Andrés Tuxtla", "cve_loc": 16, "localidad": "Calería                                                                                                       ", "ageb": "0461", "manzana": 27, "telefono": null, "correoelec": null, "www": null, "tipoUniEco": "Fijo", "latitud": 18.42939484, "longitud": -95.17836529, "fecha_alta": "2019-11" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -95.17836529, 18.42939484 ] ] } },
{ "type": "Feature", "properties": { "id": 8591188, "clee": "30003334410000011000000000S3", "nom_estab": "MODULO DE LICENCIASPARA CONDUCIR VEHICULOS", "raz_social": "IBEROL AZTECA SA DE CV", "codigo_act": 334410, "nombre_act": "Fabricación de componentes electrónicos", "per_ocu": "0 a 5 personas", "tipo_vial": "CALLE", "nom_vial": "GUADALUPE VICTORIA", "tipo_v_e_1": "CALLE", "nom_v_e_1": "PORVENIR", "tipo_v_e_2": "CALLE", "nom_v_e_2": "AMADO NERVO", "tipo_v_e_3": "CALLE", "nom_v_e_3": "BENITO BARRIOVERO", "numero_ext": 20, "letra_ext": null, "edificio": null, "edificio_e": null, "numero_int": null, "letra_int": null, "tipo_asent": "COLONIA", "nomb_asent": "CENTRO", "tipoCenCom": null, "nom_CenCom": null, "num_local": null, "cod_postal": 96000, "cve_ent": 30, "entidad": "Veracruz de Ignacio de la Llave", "cve_mun": 3, "municipio": "Acayucan", "cve_loc": 1, "localidad": "Acayucan                                                                                                      ", "ageb": "0323", "manzana": 37, "telefono": null, "correoelec": null, "www": null, "tipoUniEco": "Fijo", "latitud": 17.94912995, "longitud": -94.91670688000001, "fecha_alta": "2019-11" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -94.91670688, 17.94912995 ] ] } },
{ "type": "Feature", "properties": { "id": 9144461, "clee": "30003334410000022000000000S0", "nom_estab": "MODULO DE LICENCIAS PARA CONDUCIR", "raz_social": "IBERO AZTECA SA DE CV", "codigo_act": 334410, "nombre_act": "Fabricación de componentes electrónicos", "per_ocu": "6 a 10 personas", "tipo_vial": "CALLE", "nom_vial": "MIGUEL ALEMAN", "tipo_v_e_1": "CALLE", "nom_v_e_1": "JIMENEZ", "tipo_v_e_2": "CALLE", "nom_v_e_2": "MIGUEL HIDALGO", "tipo_v_e_3": "CALLE", "nom_v_e_3": "INDEPENDENCIA", "numero_ext": 302, "letra_ext": null, "edificio": "EDIFICIO SIN NOMBRE", "edificio_e": "PISO 1", "numero_int": null, "letra_int": "9", "tipo_asent": "BARRIO", "nomb_asent": "TAMARINDO", "tipoCenCom": null, "nom_CenCom": null, "num_local": null, "cod_postal": 96049, "cve_ent": 30, "entidad": "Veracruz de Ignacio de la Llave", "cve_mun": 3, "municipio": "Acayucan", "cve_loc": 1, "localidad": "Acayucan                                                                                                      ", "ageb": "0338", "manzana": 23, "telefono": null, "correoelec": null, "www": null, "tipoUniEco": "Fijo", "latitud": 17.94845916, "longitud": -94.90959525, "fecha_alta": "2019-11" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -94.90959525, 17.94845916 ] ] } }
]
}
