{
"type": "FeatureCollection",
"name": "IndusImpresionMas10",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": 3191435, "clee": "20043323111000013000000000U4", "nom_estab": "EDITORIAL ISTMO DOS MIL EL SUR DIARIO INDEPENDIENTE", "raz_social": "EDITORIAL ISTMO DOS MIL SA DE CV", "codigo_act": 323111, "nombre_act": "Impresión de libros, periódicos y revistas", "per_ocu": "11 a 30 personas", "tipo_vial": "CALLE", "nom_vial": "HECTOR SANCHEZ", "tipo_v_e_1": "CALLE", "nom_v_e_1": "7 DE NOVIEMBRE", "tipo_v_e_2": "CALLE", "nom_v_e_2": "JOSE MURAT", "tipo_v_e_3": "CARRETERA", "nom_v_e_3": "PANAMERICANA", "numero_ext": 0, "letra_ext": "SN", "edificio": "EDIFICIO SIN NOMBRE", "edificio_e": "OTRO (ESPECIFIQUE)", "numero_int": 0, "letra_int": null, "tipo_asent": "COLONIA", "nomb_asent": "5 DE FEBRERO", "tipoCenCom": null, "nom_CenCom": null, "num_local": null, "cod_postal": 70000, "cve_ent": 20, "entidad": "Oaxaca", "cve_mun": 43, "municipio": "Heroica Ciudad de Juchitán de Zaragoza", "cve_loc": 1, "localidad": "Juchitán de Zaragoza                                                                                          ", "ageb": "0274", "manzana": 14, "telefono": null, "correoelec": null, "www": null, "tipoUniEco": "Fijo", "latitud": 16.4471626, "longitud": -95.02335925, "fecha_alta": "2010-07" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -95.02335925, 16.4471626 ] ] } },
{ "type": "Feature", "properties": { "id": 4336366, "clee": "30039323111000053000000000S6", "nom_estab": "DIARIO GRAFICO SUR", "raz_social": null, "codigo_act": 323111, "nombre_act": "Impresión de libros, periódicos y revistas", "per_ocu": "11 a 30 personas", "tipo_vial": "CALLE", "nom_vial": "GUTIERREZ ZAMORA", "tipo_v_e_1": "CALLE", "nom_v_e_1": "CORREGIDORA", "tipo_v_e_2": "CALLE", "nom_v_e_2": "COLEGIO MILITAR", "tipo_v_e_3": "CALLE", "nom_v_e_3": "IGNACIO DE LA LLAVE", "numero_ext": 111, "letra_ext": null, "edificio": null, "edificio_e": null, "numero_int": 0, "letra_int": null, "tipo_asent": "COLONIA", "nomb_asent": "COATZACOALCOS CENTRO", "tipoCenCom": null, "nom_CenCom": null, "num_local": null, "cod_postal": 96400, "cve_ent": 30, "entidad": "Veracruz de Ignacio de la Llave", "cve_mun": 39, "municipio": "Coatzacoalcos", "cve_loc": 1, "localidad": "Coatzacoalcos                                                                                                 ", "ageb": "010A", "manzana": 30, "telefono": null, "correoelec": null, "www": null, "tipoUniEco": "Fijo", "latitud": 18.14915123, "longitud": -94.41225888, "fecha_alta": "2014-12" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -94.41225888, 18.14915123 ] ] } },
{ "type": "Feature", "properties": { "id": 4467492, "clee": "30039323119000743000000000U5", "nom_estab": "ARDIPU S.A. DE C. V.", "raz_social": "ARDIPU SA DE CV", "codigo_act": 323119, "nombre_act": "Impresión de formas continuas y otros impresos", "per_ocu": "11 a 30 personas", "tipo_vial": "CALLE", "nom_vial": "ROMAN MARIN", "tipo_v_e_1": "CALLE", "nom_v_e_1": "16 DE SEPTIEMBRE", "tipo_v_e_2": "CALLE", "nom_v_e_2": "VENUSTIANO CARRANZA", "tipo_v_e_3": "AVENIDA", "nom_v_e_3": "GENERAL ANAYA", "numero_ext": 107, "letra_ext": null, "edificio": null, "edificio_e": null, "numero_int": null, "letra_int": null, "tipo_asent": "COLONIA", "nomb_asent": "CENTRO", "tipoCenCom": null, "nom_CenCom": null, "num_local": null, "cod_postal": 96400, "cve_ent": 30, "entidad": "Veracruz de Ignacio de la Llave", "cve_mun": 39, "municipio": "Coatzacoalcos", "cve_loc": 1, "localidad": "Coatzacoalcos                                                                                                 ", "ageb": "0985", "manzana": 5, "telefono": "9212126610", "correoelec": null, "www": null, "tipoUniEco": "Fijo", "latitud": 18.14400043, "longitud": -94.41589501, "fecha_alta": "2010-07" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -94.41589501, 18.14400043 ] ] } },
{ "type": "Feature", "properties": { "id": 6412439, "clee": "30039323111000046000012746M0", "nom_estab": "DIARIO DEL ISTMO", "raz_social": "EDITORA LA VOZ DEL ISTMO SA DE CV", "codigo_act": 323111, "nombre_act": "Impresión de libros, periódicos y revistas", "per_ocu": "101 a 250 personas", "tipo_vial": "CALLE", "nom_vial": "MIGUEL HIDALGO", "tipo_v_e_1": "CALLE", "nom_v_e_1": "MARIANO ABASOLO", "tipo_v_e_2": "CALLE", "nom_v_e_2": "PEDRO MORENO", "tipo_v_e_3": "CALLE", "nom_v_e_3": "MARIANO ABASOLO", "numero_ext": 1115, "letra_ext": null, "edificio": null, "edificio_e": null, "numero_int": 0, "letra_int": null, "tipo_asent": "COLONIA", "nomb_asent": "CENTRO", "tipoCenCom": null, "nom_CenCom": null, "num_local": null, "cod_postal": 96400, "cve_ent": 30, "entidad": "Veracruz de Ignacio de la Llave", "cve_mun": 39, "municipio": "Coatzacoalcos", "cve_loc": 1, "localidad": "Coatzacoalcos                                                                                                 ", "ageb": "0966", "manzana": 12, "telefono": null, "correoelec": null, "www": "WWW.DIARIODELISTMO.COM", "tipoUniEco": "Fijo", "latitud": 18.14321272, "longitud": -94.42832928, "fecha_alta": "2010-07" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -94.42832928, 18.14321272 ] ] } }
]
}
