{
"type": "FeatureCollection",
"name": "IndusPlaticHuleMas10",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": 4345954, "clee": "30048326198000023000000000U4", "nom_estab": "SERVICIOS E IMPORTACIONES ESPECIALIZADAS", "raz_social": "SERVICIOS E IMPORTACIONES ESPECIALIZADAS SA DE CV", "codigo_act": 326198, "nombre_act": "Fabricación de otros productos de plástico con reforzamiento", "per_ocu": "11 a 30 personas", "tipo_vial": "CALLE", "nom_vial": "BENITO JUAREZ", "tipo_v_e_1": "CALLE", "nom_v_e_1": "BENITO JUAREZ", "tipo_v_e_2": "CALLE", "nom_v_e_2": "ÚRSULO GALVAN", "tipo_v_e_3": "CALLE", "nom_v_e_3": "ÚRSULO GALVÁN", "numero_ext": 130, "letra_ext": null, "edificio": null, "edificio_e": null, "numero_int": 0, "letra_int": null, "tipo_asent": "EJIDO", "nomb_asent": "ESTERO DEL PANTANO", "tipoCenCom": null, "nom_CenCom": null, "num_local": null, "cod_postal": 96343, "cve_ent": 30, "entidad": "Veracruz de Ignacio de la Llave", "cve_mun": 48, "municipio": "Cosoleacaque", "cve_loc": 11, "localidad": "Estero del Pantano                                                                                            ", "ageb": "0221", "manzana": 82, "telefono": "9212158046", "correoelec": "CONTABILIDAD@SIESA.COM.MX", "www": "WWW.SIESA.COM.MX", "tipoUniEco": "Fijo", "latitud": 18.09537615, "longitud": -94.45598414, "fecha_alta": "2014-12" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -94.45598414, 18.09537615 ] ] } },
{ "type": "Feature", "properties": { "id": 4432420, "clee": "30141326110000014000000000U1", "nom_estab": "PRODUCTOS PLASTICOS DEL GOLFO", "raz_social": null, "codigo_act": 326110, "nombre_act": "Fabricación de bolsas y películas de plástico flexible", "per_ocu": "31 a 50 personas", "tipo_vial": "AVENIDA", "nom_vial": "MANUEL A. DE LA CABADA", "tipo_v_e_1": "CALLEJON", "nom_v_e_1": "NUESTRA SEÑORA DEL CALVARIO", "tipo_v_e_2": "CALLE", "nom_v_e_2": "CENTENARIO", "tipo_v_e_3": "CARRETERA", "nom_v_e_3": "COSTERA DEL GOLFO", "numero_ext": null, "letra_ext": "SN", "edificio": null, "edificio_e": null, "numero_int": null, "letra_int": null, "tipo_asent": "COLONIA", "nomb_asent": "TRES DE MAYO", "tipoCenCom": null, "nom_CenCom": null, "num_local": null, "cod_postal": 95730, "cve_ent": 30, "entidad": "Veracruz de Ignacio de la Llave", "cve_mun": 141, "municipio": "San Andrés Tuxtla", "cve_loc": 1, "localidad": "San Andrés Tuxtla                                                                                             ", "ageb": "0599", "manzana": 35, "telefono": "2949424705", "correoelec": "PROPLASTIC1@PRODIGG.NET.MX", "www": null, "tipoUniEco": "Fijo", "latitud": 18.44857387, "longitud": -95.22538227, "fecha_alta": "2010-07" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -95.22538227, 18.44857387 ] ] } },
{ "type": "Feature", "properties": { "id": 4461134, "clee": "30039326110000023001000000U8", "nom_estab": "IDI EMPAQUES", "raz_social": "IDI EMPAQUES SA DE CV", "codigo_act": 326110, "nombre_act": "Fabricación de bolsas y películas de plástico flexible", "per_ocu": "11 a 30 personas", "tipo_vial": "CALLE", "nom_vial": "BERNARDO SIMONEEN", "tipo_v_e_1": "CALLE", "nom_v_e_1": "BELLAVISTA", "tipo_v_e_2": "CALLE", "nom_v_e_2": "18 DE MARZO", "tipo_v_e_3": "CALLE", "nom_v_e_3": "JOSÉ MARÍA CARACAS", "numero_ext": 1509, "letra_ext": null, "edificio": null, "edificio_e": null, "numero_int": null, "letra_int": null, "tipo_asent": "COLONIA", "nomb_asent": "GUADALUPE VICTORIA", "tipoCenCom": null, "nom_CenCom": null, "num_local": null, "cod_postal": 96520, "cve_ent": 30, "entidad": "Veracruz de Ignacio de la Llave", "cve_mun": 39, "municipio": "Coatzacoalcos", "cve_loc": 1, "localidad": "Coatzacoalcos                                                                                                 ", "ageb": "1023", "manzana": 12, "telefono": "9212135453", "correoelec": null, "www": null, "tipoUniEco": "Fijo", "latitud": 18.14703814, "longitud": -94.45995062, "fecha_alta": "2010-07" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -94.45995062, 18.14703814 ] ] } },
{ "type": "Feature", "properties": { "id": 6411711, "clee": "30048326212000023002012449S3", "nom_estab": "RENOVADORA ZUCA DEL SURESTE SA DE CV", "raz_social": "RENOVADORA ZUCA DEL SURESTE SA DE CV", "codigo_act": 326212, "nombre_act": "Revitalización de llantas", "per_ocu": "11 a 30 personas", "tipo_vial": "CALLE", "nom_vial": "VICENTE GUERRERO", "tipo_v_e_1": "CALLE", "nom_v_e_1": "5 DE FEBRERO", "tipo_v_e_2": "CALLE", "nom_v_e_2": "PRIMERO DE MAYO", "tipo_v_e_3": "CALLE", "nom_v_e_3": "MORELOS", "numero_ext": 0, "letra_ext": "SN", "edificio": null, "edificio_e": null, "numero_int": null, "letra_int": null, "tipo_asent": "COLONIA", "nomb_asent": "ESTERO DEL PANTANO", "tipoCenCom": null, "nom_CenCom": null, "num_local": null, "cod_postal": 96564, "cve_ent": 30, "entidad": "Veracruz de Ignacio de la Llave", "cve_mun": 48, "municipio": "Cosoleacaque", "cve_loc": 11, "localidad": "Estero del Pantano                                                                                            ", "ageb": "0221", "manzana": 20, "telefono": null, "correoelec": "CONTABILIDAD1@ZUCA.COM.MX", "www": null, "tipoUniEco": "Fijo", "latitud": 18.10421511, "longitud": -94.45318325, "fecha_alta": "2010-07" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -94.45318325, 18.10421511 ] ] } }
]
}
