{
"type": "FeatureCollection",
"name": "MaquinariaMas10",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": 6353063, "clee": "30039333999000013000006745S6", "nom_estab": "CORPORACION CONSTRUCTORA AZTECA SA DE CV", "raz_social": "CORPORACION CONSTRUCTORA AZTECA SA DE CV", "codigo_act": 333999, "nombre_act": "Fabricación de otra maquinaria y equipo para la industria en general", "per_ocu": "11 a 30 personas", "tipo_vial": "CALLE", "nom_vial": "IGNACIO ZARAGOZA", "tipo_v_e_1": "CALLE", "nom_v_e_1": "RODRÍGUEZ MALPICA", "tipo_v_e_2": "CALLE", "nom_v_e_2": "MIGUEL HIDALGO", "tipo_v_e_3": "AVENIDA", "nom_v_e_3": "IGNACIO ZARAGOZA", "numero_ext": 1406, "letra_ext": null, "edificio": null, "edificio_e": null, "numero_int": 0, "letra_int": null, "tipo_asent": "COLONIA", "nomb_asent": "CENTRO", "tipoCenCom": null, "nom_CenCom": null, "num_local": null, "cod_postal": null, "cve_ent": 30, "entidad": "Veracruz de Ignacio de la Llave", "cve_mun": 39, "municipio": "Coatzacoalcos", "cve_loc": 1, "localidad": "Coatzacoalcos                                                                                                 ", "ageb": "0966", "manzana": 17, "telefono": null, "correoelec": null, "www": "WWW.CCAZTECA.COM.MX", "tipoUniEco": "Fijo", "latitud": 18.14164989, "longitud": -94.43383885, "fecha_alta": "2014-12" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -94.43383885, 18.14164989 ] ] } },
{ "type": "Feature", "properties": { "id": 8205025, "clee": "20079333991000013000000000S1", "nom_estab": "GRUPO CONSTRUCTOR SATIRSA", "raz_social": "GRUPO CONSTRUCTOR SATIRSA SA DE CV", "codigo_act": 333991, "nombre_act": "Fabricación de equipo para soldar y soldaduras", "per_ocu": "11 a 30 personas", "tipo_vial": "AVENIDA", "nom_vial": "OLEODUCTO GENERAL LAZARO CARDENAS", "tipo_v_e_1": "CALLE", "nom_v_e_1": "MONTE ALBAN", "tipo_v_e_2": "AVENIDA", "nom_v_e_2": "OLEODUCTO GENERAL LAZARO CARDENAS", "tipo_v_e_3": "AVENIDA", "nom_v_e_3": "TORREÓN", "numero_ext": 0, "letra_ext": "SN", "edificio": null, "edificio_e": null, "numero_int": 0, "letra_int": null, "tipo_asent": "COLONIA", "nomb_asent": "CESAR LINTON", "tipoCenCom": null, "nom_CenCom": null, "num_local": null, "cod_postal": 70614, "cve_ent": 20, "entidad": "Oaxaca", "cve_mun": 79, "municipio": "Salina Cruz", "cve_loc": 1, "localidad": "Salina Cruz                                                                                                   ", "ageb": "0633", "manzana": 1, "telefono": "9711373571", "correoelec": "SATIRSA.CONTABILIDAD@HOTMAIL.COM", "www": "GRUPOSATIRSA.COM", "tipoUniEco": "Fijo", "latitud": 16.22643348, "longitud": -95.18669594000001, "fecha_alta": "2019-11" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -95.18669594, 16.22643348 ] ] } }
]
}
