var metalBasicoMenos10 = {
"type": "FeatureCollection",
"name": "MetalBasicoMenos10",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": 4340543, "clee": "30108331220000012001000000U4", "nom_estab": "CONSTUCCIONES Y SERVICIOS ZARGUT", "raz_social": "CONSTRUCCIONES Y SERVICIOS ZARGUT SA DE CV", "codigo_act": 331220, "nombre_act": "Fabricación de otros productos de hierro y acero", "per_ocu": "0 a 5 personas", "tipo_vial": "CALLE", "nom_vial": "FLORESTA", "tipo_v_e_1": "CALLE", "nom_v_e_1": "CUITAHUAC", "tipo_v_e_2": "CALLE", "nom_v_e_2": "MOTUL", "tipo_v_e_3": "CALLE", "nom_v_e_3": "FLORESTA", "numero_ext": 37, "letra_ext": null, "edificio": null, "edificio_e": null, "numero_int": 0, "letra_int": null, "tipo_asent": "COLONIA", "nomb_asent": "AZTECA", "tipoCenCom": null, "nom_CenCom": null, "num_local": null, "cod_postal": 96700, "cve_ent": 30, "entidad": "Veracruz de Ignacio de la Llave", "cve_mun": 108, "municipio": "Minatitlán", "cve_loc": 1, "localidad": "Minatitlán                                                                                                    ", "ageb": "0895", "manzana": 25, "telefono": "9222224163", "correoelec": "ZARGUT_SADECV@HOTMAIL.COM", "www": null, "tipoUniEco": "Fijo", "latitud": 18.01945893, "longitud": -94.55719142, "fecha_alta": "2014-12" }, "geometry": { "type": "Point", "coordinates": [ -94.55719142, 18.01945893 ] } },
{ "type": "Feature", "properties": { "id": 4462839, "clee": "30039332999000022011000000U8", "nom_estab": "TALLER DE MAQUILADO SIN NOMBRE", "raz_social": null, "codigo_act": 331220, "nombre_act": "Fabricación de otros productos de hierro y acero", "per_ocu": "0 a 5 personas", "tipo_vial": "CALLE", "nom_vial": "AQUILES SERDAN", "tipo_v_e_1": "CALLE", "nom_v_e_1": "DEMOCRACIA", "tipo_v_e_2": "CALLE", "nom_v_e_2": "AYUNTAMIENTO", "tipo_v_e_3": "CALLE", "nom_v_e_3": "EMILIANO ZAPATA", "numero_ext": 1515, "letra_ext": null, "edificio": null, "edificio_e": null, "numero_int": null, "letra_int": null, "tipo_asent": "COLONIA", "nomb_asent": "BENITO JUAREZ NORTE", "tipoCenCom": null, "nom_CenCom": null, "num_local": null, "cod_postal": 96576, "cve_ent": 30, "entidad": "Veracruz de Ignacio de la Llave", "cve_mun": 39, "municipio": "Coatzacoalcos", "cve_loc": 1, "localidad": "Coatzacoalcos                                                                                                 ", "ageb": "0167", "manzana": 15, "telefono": null, "correoelec": "TALLERDEMAQUILADO@HOTMAIL.COM", "www": null, "tipoUniEco": "Fijo", "latitud": 18.13488653, "longitud": -94.44918999, "fecha_alta": "2010-07" }, "geometry": { "type": "Point", "coordinates": [ -94.44918999, 18.13488653 ] } }
]
}
